# Configure Netlify builds
[build]
  command = "npm run build"
  publish = ".next"

# Configure the Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set build environment variables
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
