[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
<<<<<<< HEAD
NEXT_USE_NETLIFY_EDGE = "true"
=======
NEXT_USE_NETLIFY_EDGE = "true"
>>>>>>> 9750ebbd5d5c587312dd17cf96690558101ed14b
